/*
 * Linpak.java
 */

import com.comsol.model.*;
import com.comsol.model.util.*;

/** Model exported on May 8 2019, 14:58 by COMSOL 5.4.0.295. */
public class Linpak {

    public static Model run() {
        Model model = ModelUtil.create("Model");

        model.modelPath("F:\\Sanya\\LinPak\\COMSOL\\COMSOL 3D Model");

        model.component().create("comp1", true);

        model.component("comp1").geom().create("geom1", 3);

        model.component("comp1").mesh().create("mesh1");

        model.component("comp1").physics().create("solid", "SolidMechanics", "geom1");
        model.component("comp1").physics("solid").prop("StructuralTransientBehavior")
                .set("StructuralTransientBehavior", "Quasistatic");
        model.component("comp1").physics().create("ht", "HeatTransfer", "geom1");
        model.component("comp1").physics("ht").prop("ShapeProperty").set("order_temperature", "1");

        model.component("comp1").multiphysics().create("te1", "ThermalExpansion", 3);
        model.component("comp1").multiphysics("te1").selection().all();
        model.component("comp1").multiphysics("te1").set("Heat_physics", "ht");
        model.component("comp1").multiphysics("te1").set("Solid_physics", "solid");
        model.component("comp1").multiphysics().create("tc1", "TemperatureCoupling");
        model.component("comp1").multiphysics("tc1").set("TemperatureSource_physics", "ht");
        model.component("comp1").multiphysics("tc1").set("TemperatureDestination_physics", "solid");

        model.study().create("std1");
        model.study("std1").setGenConv(true);
        model.study("std1").create("stat", "Stationary");
        model.study("std1").feature("stat").activate("solid", true);
        model.study("std1").feature("stat").activate("ht", true);
        model.study("std1").feature("stat").activate("te1", true);
        model.study("std1").feature("stat").activate("tc1", true);

        model.component("comp1").geom("geom1").create("blk1", "Block");
        model.component("comp1").geom("geom1").feature("blk1").set("size", new int[]{40, 1, 40});
        model.component("comp1").geom("geom1").run("blk1");
        model.component("comp1").geom("geom1").run("blk1");
        model.component("comp1").geom("geom1").create("ic1", "InterpolationCurve");
        model.component("comp1").geom("geom1").feature().remove("ic1");
        model.component("comp1").geom("geom1").run("blk1");
        model.component("comp1").geom("geom1").create("blk2", "Block");
        model.component("comp1").geom("geom1").run("blk2");
        model.component("comp1").geom("geom1").feature("blk2").set("pos", new int[]{2, 0, 0});
        model.component("comp1").geom("geom1").run("blk2");
        model.component("comp1").geom("geom1").feature("blk2").set("pos", new int[]{10, 0, 0});
        model.component("comp1").geom("geom1").run("blk2");
        model.component("comp1").geom("geom1").feature("blk2").set("size", new int[]{1, 2, 1});
        model.component("comp1").geom("geom1").run("blk2");
        model.component("comp1").geom("geom1").feature("blk2").set("size", new int[]{1, 1, 2});
        model.component("comp1").geom("geom1").run("blk2");
        model.component("comp1").geom("geom1").feature("blk2").set("size", new int[]{11, 1, 2});
        model.component("comp1").geom("geom1").run("blk2");
        model.component("comp1").geom("geom1").feature("blk2").set("size", new int[]{20, 1, 2});
        model.component("comp1").geom("geom1").run("blk2");
        model.component("comp1").geom("geom1").run("blk2");
        model.component("comp1").geom("geom1").feature().create("ext1", "Extrude");
        model.component("comp1").geom("geom1").feature("ext1").selection("inputface").set("blk2", 3);
        model.component("comp1").geom("geom1").feature("ext1").set("reverse", true);
        model.component("comp1").geom("geom1").feature().remove("ext1");
        model.component("comp1").geom("geom1").run("blk2");
        model.component("comp1").geom("geom1").feature().create("rev1", "Revolve");
        model.component("comp1").geom("geom1").feature("rev1").set("angtype", "full");
        model.component("comp1").geom("geom1").run("blk2");
        model.component("comp1").geom("geom1").feature().remove("rev1");
        model.component("comp1").geom("geom1").run("blk2");
        model.component("comp1").geom("geom1").create("dif1", "Difference");
        model.component("comp1").geom("geom1").feature("dif1").selection("input").set("blk2");
        model.component("comp1").geom("geom1").feature("dif1").selection("input2").set("blk1");
        model.component("comp1").geom("geom1").feature("dif1").selection("input").remove("blk2");
        model.component("comp1").geom("geom1").feature("dif1").selection("input2").remove("blk1");
        model.component("comp1").geom("geom1").feature("dif1").selection("input").set("blk1");
        model.component("comp1").geom("geom1").feature("dif1").selection("input2").set("blk2");
        model.component("comp1").geom("geom1").run("dif1");
        model.component("comp1").geom("geom1").feature().remove("dif1");
        model.component("comp1").geom("geom1").run("fin");
        model.component("comp1").geom("geom1").run("blk2");
        model.component("comp1").geom("geom1").create("blk3", "Block");
        model.component("comp1").geom("geom1").feature("blk3").set("size", new int[]{20, 1, 2});
        model.component("comp1").geom("geom1").run("blk3");
        model.component("comp1").geom("geom1").feature("blk3").set("size", new int[]{2, 1, 2});
        model.component("comp1").geom("geom1").run("blk3");
        model.component("comp1").geom("geom1").feature("blk3").set("pos", new int[]{0, 0, 10});
        model.component("comp1").geom("geom1").run("blk3");
        model.component("comp1").geom("geom1").feature("blk3").set("size", new int[]{2, 1, 20});
        model.component("comp1").geom("geom1").run("blk3");
        model.component("comp1").geom("geom1").run("blk3");
        model.component("comp1").geom("geom1").create("blk4", "Block");
        model.component("comp1").geom("geom1").feature("blk4").set("size", new int[]{2, 1, 1});
        model.component("comp1").geom("geom1").run("blk4");
        model.component("comp1").geom("geom1").feature("blk4").set("size", new int[]{2, 1, 2});
        model.component("comp1").geom("geom1").run("blk4");
        model.component("comp1").geom("geom1").feature("blk4").set("pos", new int[]{40, 0, 0});
        model.component("comp1").geom("geom1").run("blk4");
        model.component("comp1").geom("geom1").feature("blk4").set("pos", new int[]{38, 0, 0});
        model.component("comp1").geom("geom1").run("blk4");
        model.component("comp1").geom("geom1").feature("blk4").set("pos", new int[]{38, 0, 20});
        model.component("comp1").geom("geom1").run("blk4");
        model.component("comp1").geom("geom1").feature("blk4").set("pos", new int[]{38, 0, 10});
        model.component("comp1").geom("geom1").run("blk4");
        model.component("comp1").geom("geom1").feature("blk4").set("pos", new int[]{38, 0, 2});
        model.component("comp1").geom("geom1").run("blk4");
        model.component("comp1").geom("geom1").feature("blk4").set("pos", new int[]{38, 0, 0});
        model.component("comp1").geom("geom1").run("blk4");
        model.component("comp1").geom("geom1").feature("blk4").set("pos", new int[]{38, 0, 10});
        model.component("comp1").geom("geom1").run("blk4");
        model.component("comp1").geom("geom1").feature("blk4").set("size", new int[]{2, 1, 20});
        model.component("comp1").geom("geom1").run("blk4");
        model.component("comp1").geom("geom1").run("blk4");
        model.component("comp1").geom("geom1").create("blk5", "Block");
        model.component("comp1").geom("geom1").feature("blk5").set("size", new int[]{20, 1, 2});
        model.component("comp1").geom("geom1").run("blk5");
        model.component("comp1").geom("geom1").feature("blk5").set("pos", new int[]{10, 0, 0});
        model.component("comp1").geom("geom1").run("blk5");
        model.component("comp1").geom("geom1").feature("blk5").set("pos", new int[]{10, 0, 40});
        model.component("comp1").geom("geom1").run("blk5");
        model.component("comp1").geom("geom1").feature("blk5").set("pos", new int[]{10, 0, 38});
        model.component("comp1").geom("geom1").run("blk5");
        model.component("comp1").geom("geom1").run("blk5");
        model.component("comp1").geom("geom1").create("sph1", "Sphere");
        model.component("comp1").geom("geom1").feature("sph1").set("r", 3);
        model.component("comp1").geom("geom1").feature().remove("sph1");
        model.component("comp1").geom("geom1").run("blk5");
        model.component("comp1").geom("geom1").create("blk6", "Block");
        model.component("comp1").geom("geom1").feature("blk6").set("rot", 1);
        model.component("comp1").geom("geom1").run("blk6");
        model.component("comp1").geom("geom1").feature("blk6").set("rot", "");
        model.component("comp1").geom("geom1").run("blk5");
        model.component("comp1").geom("geom1").feature("blk6").set("rot", 0);
        model.component("comp1").geom("geom1").run("blk6");
        model.component("comp1").geom("geom1").feature("blk6").set("base", "corner");
        model.component("comp1").geom("geom1").run("blk6");
        model.component("comp1").geom("geom1").feature().remove("blk6");
        model.component("comp1").geom("geom1").run("blk5");
        model.component("comp1").geom("geom1").create("cyl1", "Cylinder");
        model.component("comp1").geom("geom1").run("cyl1");
        model.component("comp1").geom("geom1").run("cyl1");
        model.component("comp1").geom("geom1").feature("cyl1").set("pos", new int[]{1, 0, 0});
        model.component("comp1").geom("geom1").run("cyl1");
        model.component("comp1").geom("geom1").feature("cyl1").set("pos", new int[]{1, 2, 0});
        model.component("comp1").geom("geom1").run("cyl1");
        model.component("comp1").geom("geom1").feature("cyl1").set("rot", 90);
        model.component("comp1").geom("geom1").run("cyl1");
        model.component("comp1").geom("geom1").feature("cyl1").set("rot", 180);
        model.component("comp1").geom("geom1").run("cyl1");
        model.component("comp1").geom("geom1").feature("cyl1").set("rot", 45);
        model.component("comp1").geom("geom1").run("cyl1");
        model.component("comp1").geom("geom1").feature("cyl1").set("rot", 369);
        model.component("comp1").geom("geom1").run("cyl1");
        model.component("comp1").geom("geom1").feature().remove("cyl1");
        model.component("comp1").geom("geom1").run("blk5");
        model.component("comp1").geom("geom1").create("cyl1", "Cylinder");
        model.component("comp1").geom("geom1").run("cyl1");
        model.component("comp1").geom("geom1").feature().remove("cyl1");
        model.component("comp1").geom("geom1").run("blk5");
        model.component("comp1").geom("geom1").create("cyl1", "Cylinder");
        model.component("comp1").geom("geom1").run("cyl1");
        model.component("comp1").geom("geom1").feature("cyl1").set("axistype", "y");
        model.component("comp1").geom("geom1").run("cyl1");
        model.component("comp1").geom("geom1").feature("cyl1").set("pos", new int[]{1, 0, 0});
        model.component("comp1").geom("geom1").run("cyl1");
        model.component("comp1").geom("geom1").feature("cyl1").set("pos", new int[]{1, 1, 0});
        model.component("comp1").geom("geom1").run("cyl1");
        model.component("comp1").geom("geom1").feature("cyl1").set("pos", new int[]{1, 0, 0});
        model.component("comp1").geom("geom1").run("cyl1");
        model.component("comp1").geom("geom1").feature("cyl1").set("pos", new int[]{1, 0, 1});
        model.component("comp1").geom("geom1").run("cyl1");
        model.component("comp1").geom("geom1").feature("cyl1").set("pos", new int[]{1, 0, 5});
        model.component("comp1").geom("geom1").run("cyl1");
        model.component("comp1").geom("geom1").feature("cyl1").set("pos", new int[]{5, 0, 5});
        model.component("comp1").geom("geom1").run("cyl1");
        model.component("comp1").geom("geom1").feature("cyl1").set("r", 3);
        model.component("comp1").geom("geom1").run("cyl1");
        model.component("comp1").geom("geom1").run("cyl1");
        model.component("comp1").geom("geom1").create("cyl2", "Cylinder");
        model.component("comp1").geom("geom1").run("cyl2");
        model.component("comp1").geom("geom1").feature("cyl2").set("axistype", "y");
        model.component("comp1").geom("geom1").run("cyl2");
        model.component("comp1").geom("geom1").feature("cyl2").set("pos", new int[]{1, 0, 1});
        model.component("comp1").geom("geom1").run("cyl2");
        model.component("comp1").geom("geom1").feature("cyl2").set("pos", new int[]{5, 0, 5});
        model.component("comp1").geom("geom1").run("cyl2");
        model.component("comp1").geom("geom1").feature("cyl2").set("r", 3);
        model.component("comp1").geom("geom1").run("cyl2");
        model.component("comp1").geom("geom1").feature("cyl2").set("pos", new int[]{35, 0, 5});
        model.component("comp1").geom("geom1").run("cyl2");
        model.component("comp1").geom("geom1").feature().copy("cyl3", "geom1/cyl1");
        model.component("comp1").geom("geom1").run("cyl3");
        model.component("comp1").geom("geom1").feature("cyl3").set("pos", new int[]{5, 0, 35});
        model.component("comp1").geom("geom1").run("cyl3");
        model.component("comp1").geom("geom1").feature().copy("cyl4", "geom1/cyl2");
        model.component("comp1").geom("geom1").run("cyl4");
        model.component("comp1").geom("geom1").feature("cyl4").set("pos", new int[]{35, 0, 35});
        model.component("comp1").geom("geom1").run("cyl4");
        model.component("comp1").geom("geom1").feature("blk1").set("size", new double[]{40, 3.5, 40});
        model.component("comp1").geom("geom1").run("blk1");
        model.component("comp1").geom("geom1").feature("blk2").set("size", new double[]{20, 3.5, 2});
        model.component("comp1").geom("geom1").run("blk2");
        model.component("comp1").geom("geom1").feature("blk3").set("size", new double[]{2, 3.5, 20});
        model.component("comp1").geom("geom1").run("blk3");
        model.component("comp1").geom("geom1").feature("blk4").set("size", new double[]{2, 3.5, 20});
        model.component("comp1").geom("geom1").run("blk4");
        model.component("comp1").geom("geom1").feature("blk5").set("size", new double[]{20, 3.5, 2});
        model.component("comp1").geom("geom1").run("blk5");
        model.component("comp1").geom("geom1").feature("cyl1").set("pos", new int[]{5, 0, 5});
        model.component("comp1").geom("geom1").run("cyl1");
        model.component("comp1").geom("geom1").feature("cyl1").set("pos", new int[]{5, 0, 5});
        model.component("comp1").geom("geom1").run("cyl1");
        model.component("comp1").geom("geom1").feature("cyl1").set("h", 3.5);
        model.component("comp1").geom("geom1").run("cyl1");
        model.component("comp1").geom("geom1").feature("cyl2").set("h", 3.5);
        model.component("comp1").geom("geom1").run("cyl2");
        model.component("comp1").geom("geom1").feature("cyl3").set("h", 3.5);
        model.component("comp1").geom("geom1").run("cyl3");
        model.component("comp1").geom("geom1").feature("cyl4").set("h", 3.5);
        model.component("comp1").geom("geom1").run("cyl4");
        model.component("comp1").geom("geom1").run("cyl4");
        model.component("comp1").geom("geom1").create("dif1", "Difference");
        model.component("comp1").geom("geom1").feature("dif1").selection("input").set("blk1");
        model.component("comp1").geom("geom1").feature("dif1").selection("input2")
                .set("blk2", "blk3", "blk4", "blk5", "cyl1", "cyl2", "cyl3", "cyl4");
        model.component("comp1").geom("geom1").run("dif1");
        model.component("comp1").geom("geom1").run("dif1");
        model.component("comp1").geom("geom1").create("blk6", "Block");
        model.component("comp1").geom("geom1").run("blk6");
        model.component("comp1").geom("geom1").feature("blk6").set("pos", new double[]{9.5, 0, 0});
        model.component("comp1").geom("geom1").run("blk6");
        model.component("comp1").geom("geom1").feature("blk6").set("pos", new double[]{9.5, 0, 9.5});
        model.component("comp1").geom("geom1").run("blk6");
        model.component("comp1").geom("geom1").feature("blk6").set("size", new int[]{21, 1, 21});
        model.component("comp1").geom("geom1").run("blk6");
        model.component("comp1").geom("geom1").lengthUnit("mm");
        model.component("comp1").geom("geom1").run("fin");
        model.component("comp1").geom("geom1").feature("blk6").set("size", new double[]{21, 0.12, 21});
        model.component("comp1").geom("geom1").run("blk6");
        model.component("comp1").geom("geom1").feature("blk6").set("pos", new double[]{9.5, 0.12, 9.5});
        model.component("comp1").geom("geom1").run("blk6");
        model.component("comp1").geom("geom1").feature("blk6").set("pos", new double[]{9.5, -0.12, 9.5});
        model.component("comp1").geom("geom1").run("blk6");
        model.component("comp1").geom("geom1").feature().copy("blk7", "geom1/blk6");
        model.component("comp1").geom("geom1").run("blk7");
        model.component("comp1").geom("geom1").feature("blk7").set("size", new double[]{21, 0.145, 21});
        model.component("comp1").geom("geom1").run("blk7");
        model.component("comp1").geom("geom1").feature("blk7").set("pos", new double[]{9.5, -0.145, 9.5});
        model.component("comp1").geom("geom1").run("blk7");
        model.component("comp1").geom("geom1").feature("blk7").set("pos", new double[]{9.5, 0.145, 9.5});
        model.component("comp1").geom("geom1").run("blk7");
        model.component("comp1").geom("geom1").feature().remove("blk7");
        model.component("comp1").geom("geom1").feature("blk6").set("size", new double[]{21, 3.5, 21});
        model.component("comp1").geom("geom1").feature("blk6").set("pos", new double[]{9.5, 3.5, 9.5});
        model.component("comp1").geom("geom1").run("blk6");
        model.component("comp1").geom("geom1").feature("blk6").set("size", new double[]{21, 0.12, 21});
        model.component("comp1").geom("geom1").run("blk6");
        model.component("comp1").geom("geom1").feature().copy("blk7", "geom1/blk6");
        model.component("comp1").geom("geom1").run("blk7");
        model.component("comp1").geom("geom1").feature("blk7").set("pos", new double[]{9.5, 3.62, 9.5});
        model.component("comp1").geom("geom1").run("blk7");
        model.component("comp1").geom("geom1").feature("blk7").set("size", new double[]{21, 0.025, 21});
        model.component("comp1").geom("geom1").run("blk7");
        model.component("comp1").geom("geom1").feature().copy("blk8", "geom1/blk7");
        model.component("comp1").geom("geom1").run("blk8");
        model.component("comp1").geom("geom1").feature("blk8").set("pos", new String[]{"9.5", "3.62+0.025", "9.5"});
        model.component("comp1").geom("geom1").run("blk8");
        model.component("comp1").geom("geom1").feature("blk8").set("size", new double[]{21, 0.038, 21});
        model.component("comp1").geom("geom1").run("blk8");
        model.component("comp1").geom("geom1").run("blk8");
        model.component("comp1").geom("geom1").create("blk9", "Block");
        model.component("comp1").geom("geom1").feature("blk9").set("pos", new int[]{10, 0, 10});
        model.component("comp1").geom("geom1").run("blk9");
        model.component("comp1").geom("geom1").feature("blk9")
                .set("pos", new String[]{"10", "3.5+0.12+0.025+0.038", "10"});
        model.component("comp1").geom("geom1").run("blk9");
        model.component("comp1").geom("geom1").feature("blk9").set("layerback", false);
        model.component("comp1").geom("geom1").feature("blk9").set("layerfront", true);
        model.component("comp1").geom("geom1").feature("blk9").set("layerbottom", false);
        model.component("comp1").geom("geom1").run("blk9");
        model.component("comp1").geom("geom1").feature("blk9").set("layerbottom", true);
        model.component("comp1").geom("geom1").feature("blk9").set("layerfront", false);
        model.component("comp1").geom("geom1").run("blk9");
        model.component("comp1").geom("geom1").feature("blk9").set("size", new double[]{3.3, 1, 1});
        model.component("comp1").geom("geom1").run("blk9");
        model.component("comp1").geom("geom1").feature("blk9").set("size", new double[]{3.3, 1, 20});
        model.component("comp1").geom("geom1").run("blk9");
        model.component("comp1").geom("geom1").feature("blk9").set("size", new double[]{3.3, 0.025, 20});
        model.component("comp1").geom("geom1").run("blk9");
        model.component("comp1").geom("geom1").feature().copy("blk10", "geom1/blk9");
        model.component("comp1").geom("geom1").run("blk10");
        model.component("comp1").geom("geom1").feature("blk10").setIndex("pos", 11.9, 0);
        model.component("comp1").geom("geom1").run("blk10");
        model.component("comp1").geom("geom1").feature("blk10").setIndex("pos", 10, 0);
        model.component("comp1").geom("geom1").run("blk10");
        model.component("comp1").geom("geom1").feature("blk10").setIndex("pos", 15.2, 0);
        model.component("comp1").geom("geom1").run("blk10");
        model.component("comp1").geom("geom1").feature("blk10").set("size", new double[]{11.8, 0.025, 20});
        model.component("comp1").geom("geom1").run("blk10");
        model.component("comp1").geom("geom1").feature("blk10").set("size", new double[]{11.8, 0.025, 6.6});
        model.component("comp1").geom("geom1").run("blk10");
        model.component("comp1").geom("geom1").feature().copy("blk11", "geom1/blk10");
        model.component("comp1").geom("geom1").run("blk11");
        model.component("comp1").geom("geom1").feature("blk11").setIndex("pos", 15.5, 0);
        model.component("comp1").geom("geom1").run("blk11");
        model.component("comp1").geom("geom1").feature("blk11").setIndex("pos", 17.7, 2);
        model.component("comp1").geom("geom1").run("blk11");
        model.component("comp1").geom("geom1").feature("blk11").set("size", new double[]{7.3, 0.025, 6.6});
        model.component("comp1").geom("geom1").run("blk11");
        model.component("comp1").geom("geom1").feature("blk11").set("size", new double[]{7.3, 0.025, 4.3});
        model.component("comp1").geom("geom1").run("blk11");
        model.component("comp1").geom("geom1").feature().copy("blk12", "geom1/blk11");
        model.component("comp1").geom("geom1").feature("blk12").setIndex("pos", 15.3, 0);
        model.component("comp1").geom("geom1").run("blk12");
        model.component("comp1").geom("geom1").feature("blk12").setIndex("pos", 23, 2);
        model.component("comp1").geom("geom1").run("blk12");
        model.component("comp1").geom("geom1").feature("blk12").set("size", new double[]{11.7, 0.025, 4.3});
        model.component("comp1").geom("geom1").run("blk12");
        model.component("comp1").geom("geom1").feature("blk12").set("size", new double[]{11.7, 0.025, 7});
        model.component("comp1").geom("geom1").run("blk12");
        model.component("comp1").geom("geom1").feature().copy("blk13", "geom1/blk12");
        model.component("comp1").geom("geom1").feature("blk13").setIndex("pos", 23.3, 0);
        model.component("comp1").geom("geom1").run("blk13");
        model.component("comp1").geom("geom1").feature("blk13").setIndex("pos", 18, 2);
        model.component("comp1").geom("geom1").run("blk13");
        model.component("comp1").geom("geom1").feature("blk13").set("size", new double[]{3.7, 0.025, 7});
        model.component("comp1").geom("geom1").run("blk13");
        model.component("comp1").geom("geom1").feature("blk13").set("size", new double[]{3.7, 0.025, 5});
        model.component("comp1").geom("geom1").run("blk13");
        model.component("comp1").geom("geom1").run("blk13");
        model.component("comp1").geom("geom1").create("uni1", "Union");
        model.component("comp1").geom("geom1").feature("uni1").selection("input").set("blk12", "blk13");
        model.component("comp1").geom("geom1").run("uni1");
        model.component("comp1").geom("geom1").run("fin");
        model.component("comp1").geom("geom1").feature().copy("blk14", "geom1/blk10");
        model.component("comp1").geom("geom1").feature("blk14")
                .set("pos", new String[]{"15.2", "3.5+0.12+0.025+0.038+0.025", "10"});
        model.component("comp1").geom("geom1").run("blk14");
        model.component("comp1").geom("geom1").feature("blk14").setIndex("pos", 15.75, 0);
        model.component("comp1").geom("geom1").run("blk14");
        model.component("comp1").geom("geom1").feature("blk14").setIndex("pos", 11.57, 2);
        model.component("comp1").geom("geom1").run("blk14");
        model.component("comp1").geom("geom1").feature("blk14").set("size", new double[]{3.08, 0.025, 3.08});
        model.component("comp1").geom("geom1").run("blk14");
        model.component("comp1").geom("geom1").feature("blk14").set("size", new double[]{3.08, 0.05, 3.08});
        model.component("comp1").geom("geom1").run("blk14");
        model.component("comp1").geom("geom1").feature().copy("blk15", "geom1/blk14");
        model.component("comp1").geom("geom1").feature("blk15")
                .set("pos", new String[]{"15.75", "3.5+0.12+0.025+0.038+0.025+0.05", "11.57"});
        model.component("comp1").geom("geom1").run("blk15");
        model.component("comp1").geom("geom1").feature("blk15").set("size", new double[]{3.08, 0.38, 3.08});
        model.component("comp1").geom("geom1").run("blk15");
        model.component("comp1").geom("geom1").feature().copy("blk16", "geom1/blk15");
        model.component("comp1").geom("geom1").feature("blk16").setIndex("pos", "11.57+25", 2);
        model.component("comp1").geom("geom1").run("blk16");
        model.component("comp1").geom("geom1").feature("blk16").setIndex("pos", 25, 2);
        model.component("comp1").geom("geom1").run("blk16");
        model.component("comp1").geom("geom1").run("blk16");
        model.component("comp1").geom("geom1").feature().copy("blk17", "geom1/blk15");
        model.component("comp1").geom("geom1").run("blk17");
        model.component("comp1").geom("geom1").feature("blk17").setIndex("pos", 25, 2);
        model.component("comp1").geom("geom1").run("blk17");
        model.component("comp1").geom("geom1").feature().remove("blk17");
        model.component("comp1").geom("geom1").run("fin");
        model.component("comp1").geom("geom1").feature().remove("blk16");
        model.component("comp1").geom("geom1").run("fin");
        model.component("comp1").geom("geom1").feature().copy("blk16", "geom1/blk14");
        model.component("comp1").geom("geom1").feature("blk16").setIndex("pos", 25, 2);
        model.component("comp1").geom("geom1").run("blk16");
        model.component("comp1").geom("geom1").feature().copy("blk17", "geom1/blk15");
        model.component("comp1").geom("geom1").run("blk17");
        model.component("comp1").geom("geom1").feature("blk17").setIndex("pos", 25, 2);
        model.component("comp1").geom("geom1").run("blk17");
        model.component("comp1").geom("geom1").run("blk17");
        model.component("comp1").geom("geom1").feature().copy("blk18", "geom1/blk14");
        model.component("comp1").geom("geom1").feature("blk18").setIndex("pos", 20, 0);
        model.component("comp1").geom("geom1").run("blk18");
        model.component("comp1").geom("geom1").feature("blk18").setIndex("pos", 11.6, 2);
        model.component("comp1").geom("geom1").run("blk18");
        model.component("comp1").geom("geom1").feature("blk18").setIndex("pos", 10, 2);
        model.component("comp1").geom("geom1").run("blk18");
        model.component("comp1").geom("geom1").feature("blk18").setIndex("pos", 11, 2);
        model.component("comp1").geom("geom1").run("blk18");
        model.component("comp1").geom("geom1").feature("blk18").set("size", new double[]{6.44, 0.05, 3.08});
        model.component("comp1").geom("geom1").run("blk18");
        model.component("comp1").geom("geom1").feature("blk18").set("size", new double[]{6.44, 0.05, 4.04});
        model.component("comp1").geom("geom1").run("blk18");
        model.component("comp1").geom("geom1").feature("blk18").setIndex("pos", 11.5, 2);
        model.component("comp1").geom("geom1").run("blk18");
        model.component("comp1").geom("geom1").feature("blk18").setIndex("pos", 11.1, 2);
        model.component("comp1").geom("geom1").run("blk18");
        model.component("comp1").geom("geom1").feature().copy("blk19", "geom1/blk15");
        model.component("comp1").geom("geom1").feature("blk19").setIndex("pos", 20, 0);
        model.component("comp1").geom("geom1").run("blk19");
        model.component("comp1").geom("geom1").feature("blk19").setIndex("pos", 11.1, 2);
        model.component("comp1").geom("geom1").run("blk19");
        model.component("comp1").geom("geom1").feature("blk19").set("size", new double[]{6.44, 0.38, 4.04});
        model.component("comp1").geom("geom1").run("blk19");
        model.component("comp1").geom("geom1").feature().copy("blk20", "geom1/blk16");
        model.component("comp1").geom("geom1").run("blk20");
        model.component("comp1").geom("geom1").feature("blk20").setIndex("pos", 24.765, 2);
        model.component("comp1").geom("geom1").run("blk20");
        model.component("comp1").geom("geom1").feature("blk20").setIndex("pos", 20, 0);
        model.component("comp1").geom("geom1").run("blk20");
        model.component("comp1").geom("geom1").feature("blk20").set("size", new double[]{6.44, 0.05, 4.04});
        model.component("comp1").geom("geom1").run("blk20");
        model.component("comp1").geom("geom1").feature().copy("blk21", "geom1/blk17");
        model.component("comp1").geom("geom1").run("blk21");
        model.component("comp1").geom("geom1").feature("blk21").setIndex("pos", 20, 0);
        model.component("comp1").geom("geom1").run("blk21");
        model.component("comp1").geom("geom1").feature("blk21").setIndex("pos", 24.765, 2);
        model.component("comp1").geom("geom1").run("blk21");
        model.component("comp1").geom("geom1").feature("blk21").set("size", new double[]{6.44, 0.38, 4.04});
        model.component("comp1").geom("geom1").run("blk21");
        model.component("comp1").geom("geom1").feature().copy("blk22", "geom1/blk14");
        model.component("comp1").geom("geom1").run("blk22");
        model.component("comp1").geom("geom1").feature("blk22").setIndex("pos", 11.1, 0);
        model.component("comp1").geom("geom1").run("blk22");
        model.component("comp1").geom("geom1").feature("blk22").setIndex("pos", 19.8, 2);
        model.component("comp1").geom("geom1").run("blk22");
        model.component("comp1").geom("geom1").feature("blk22").set("size", new double[]{2.2, 0.05, 1.2});
        model.component("comp1").geom("geom1").run("blk22");
        model.component("comp1").geom("geom1").feature("blk22").set("size", new double[]{1.2, 0.05, 2.2});
        model.component("comp1").geom("geom1").run("blk22");
        model.component("comp1").geom("geom1").feature("blk22").set("size", new double[]{1.2, 0.1, 2.2});
        model.component("comp1").geom("geom1").run("blk22");
        model.component("comp1").geom("geom1").feature().copy("blk23", "geom1/blk22");
        model.component("comp1").geom("geom1").feature("blk23")
                .set("pos", new String[]{"11.1", "3.5+0.12+0.025+0.038+0.025+0.1", "19.8"});
        model.component("comp1").geom("geom1").run("blk23");
        model.component("comp1").geom("geom1").feature("blk23").set("size", new double[]{0.15, 0.1, 2.2});
        model.component("comp1").geom("geom1").run("blk23");
        model.component("comp1").geom("geom1").feature("blk23").set("size", new double[]{0.15, 1.5, 2.2});
        model.component("comp1").geom("geom1").run("blk23");
        model.component("comp1").geom("geom1").feature("blk22").set("size", new double[]{1.5, 0.1, 2.2});
        model.component("comp1").geom("geom1").run("blk22");
        model.component("comp1").geom("geom1").run("blk22");
        model.component("comp1").geom("geom1").runPre("fin");
        model.component("comp1").geom("geom1").feature().copy("blk24", "geom1/blk22");
        model.component("comp1").geom("geom1").run("blk24");
        model.component("comp1").geom("geom1").feature("blk24").setIndex("pos", 20.53, 0);
        model.component("comp1").geom("geom1").run("blk24");
        model.component("comp1").geom("geom1").feature("blk24").setIndex("pos", 18.55, 2);
        model.component("comp1").geom("geom1").run("blk24");
        model.component("comp1").geom("geom1").feature().copy("blk25", "geom1/blk23");
        model.component("comp1").geom("geom1").feature("blk25").setIndex("pos", 20.53, 0);
        model.component("comp1").geom("geom1").feature("blk25").setIndex("pos", 18.55, 2);
        model.component("comp1").geom("geom1").run("blk25");
        model.component("comp1").geom("geom1").feature().copy("blk26", "geom1/blk24");
        model.component("comp1").geom("geom1").feature("blk26").setIndex("pos", 21.2, 0);
        model.component("comp1").geom("geom1").run("blk26");
        model.component("comp1").geom("geom1").feature("blk26").setIndex("pos", 23.3, 0);
        model.component("comp1").geom("geom1").run("blk26");

        return model;
    }

    public static Model run2(Model model) {
        model.component("comp1").geom("geom1").feature("blk26").setIndex("pos", 24, 0);
        model.component("comp1").geom("geom1").run("blk26");
        model.component("comp1").geom("geom1").feature("blk26").setIndex("pos", 23.7, 0);
        model.component("comp1").geom("geom1").run("blk26");
        model.component("comp1").geom("geom1").feature().copy("blk27", "geom1/blk25");
        model.component("comp1").geom("geom1").feature("blk27").setIndex("pos", 23.7, 0);
        model.component("comp1").geom("geom1").run("blk27");
        model.component("comp1").geom("geom1").feature("blk27").setIndex("pos", "23.7+2.2", 0);
        model.component("comp1").geom("geom1").run("blk27");
        model.component("comp1").geom("geom1").feature("blk27").setIndex("pos", 22, 0);
        model.component("comp1").geom("geom1").run("blk27");
        model.component("comp1").geom("geom1").feature("blk27").setIndex("pos", 23, 0);
        model.component("comp1").geom("geom1").run("blk27");
        model.component("comp1").geom("geom1").feature("blk27").setIndex("pos", 24, 0);
        model.component("comp1").geom("geom1").run("blk27");
        model.component("comp1").geom("geom1").feature("blk27").setIndex("pos", 23.7, 0);
        model.component("comp1").geom("geom1").run("blk27");
        model.component("comp1").geom("geom1").feature("blk27").setIndex("pos", "23.7+0.15", 0);
        model.component("comp1").geom("geom1").run("blk27");
        model.component("comp1").geom("geom1").feature("blk27").setIndex("pos", "23.7+2.2", 0);
        model.component("comp1").geom("geom1").run("blk27");
        model.component("comp1").geom("geom1").feature("blk27").setIndex("pos", 23.7, 0);
        model.component("comp1").geom("geom1").run("blk27");
        model.component("comp1").geom("geom1").feature("blk25").setIndex("pos", "20.53+2.2", 0);
        model.component("comp1").geom("geom1").run("blk25");
        model.component("comp1").geom("geom1").runPre("fin");
        model.component("comp1").geom("geom1").feature("blk25").setIndex("pos", "20.53+2", 0);
        model.component("comp1").geom("geom1").run("blk25");
        model.component("comp1").geom("geom1").runPre("fin");
        model.component("comp1").geom("geom1").feature("blk25").setIndex("pos", 21, 0);
        model.component("comp1").geom("geom1").run("blk25");
        model.component("comp1").geom("geom1").runPre("fin");
        model.component("comp1").geom("geom1").feature("blk25").setIndex("pos", 22, 0);
        model.component("comp1").geom("geom1").run("blk25");
        model.component("comp1").geom("geom1").runPre("fin");
        model.component("comp1").geom("geom1").feature("blk25").setIndex("pos", 21.5, 0);
        model.component("comp1").geom("geom1").run("blk25");
        model.component("comp1").geom("geom1").runPre("fin");
        model.component("comp1").geom("geom1").feature("blk25").setIndex("pos", 21.8, 0);
        model.component("comp1").geom("geom1").runPre("fin");
        model.component("comp1").geom("geom1").feature("blk25").setIndex("pos", 21.85, 0);
        model.component("comp1").geom("geom1").runPre("fin");
        model.component("comp1").geom("geom1").feature("blk25").setIndex("pos", 21.87, 0);
        model.component("comp1").geom("geom1").runPre("fin");
        model.component("comp1").geom("geom1").feature("blk25").setIndex("pos", 21.89, 0);
        model.component("comp1").geom("geom1").runPre("fin");
        model.component("comp1").geom("geom1").feature("blk25").setIndex("pos", 21.88, 0);
        model.component("comp1").geom("geom1").runPre("fin");
        model.component("comp1").geom("geom1").feature().copy("blk28", "geom1/blk14");
        model.component("comp1").geom("geom1").run("blk28");
        model.component("comp1").geom("geom1").feature("blk28").setIndex("pos", 27.5, 0);
        model.component("comp1").geom("geom1").run("blk28");
        model.component("comp1").geom("geom1").feature("blk28").set("size", new double[]{2.5, 0.05, 2.5});
        model.component("comp1").geom("geom1").run("blk28");
        model.component("comp1").geom("geom1").feature().copy("blk29", "geom1/blk28");
        model.component("comp1").geom("geom1").feature("blk29").setIndex("pos", 13.7, 2);
        model.component("comp1").geom("geom1").run("blk29");
        model.component("comp1").geom("geom1").feature("blk28").setIndex("pos", 11, 2);
        model.component("comp1").geom("geom1").run("blk28");
        model.component("comp1").geom("geom1").runPre("fin");
        model.component("comp1").geom("geom1").feature("blk28").setIndex("pos", 10.3, 2);
        model.component("comp1").geom("geom1").runPre("fin");
        model.component("comp1").geom("geom1").feature().copy("blk30", "geom1/blk29");
        model.component("comp1").geom("geom1").feature("blk30").setIndex("pos", 23.8, 2);
        model.component("comp1").geom("geom1").runPre("fin");
        model.component("comp1").geom("geom1").feature().copy("blk31", "geom1/blk29");
        model.component("comp1").geom("geom1").feature("blk31").setIndex("pos", 27.1, 2);
        model.component("comp1").geom("geom1").runPre("fin");
        model.component("comp1").geom("geom1").feature().copy("blk32", "geom1/blk26");
        model.component("comp1").geom("geom1").run("blk32");
        model.component("comp1").geom("geom1").feature("blk32").setIndex("pos", 11.3, 2);
        model.component("comp1").geom("geom1").runPre("fin");
        model.component("comp1").geom("geom1").run("blk32");
        model.component("comp1").geom("geom1").feature("blk32").setIndex("pos", 28.4, 0);
        model.component("comp1").geom("geom1").runPre("fin");
        model.component("comp1").geom("geom1").feature().remove("blk32");
        model.component("comp1").geom("geom1").feature("blk16").set("selresult", true);
//    model.component("comp1").geom("geom1").feature("blk16").set("color", "3");
        model.component("comp1").geom("geom1").runPre("fin");
        model.component("comp1").geom("geom1").feature("blk17").set("selresult", true);
        model.component("comp1").geom("geom1").feature("blk17").set("selresultshow", "all");
//    model.component("comp1").geom("geom1").feature("blk17").set("color", "10");
        model.component("comp1").geom("geom1").feature("blk17").set("selresult", false);
        model.component("comp1").geom("geom1").feature("blk16").set("selresult", false);
        model.component("comp1").geom("geom1").feature("blk18").set("selresult", true);
//    model.component("comp1").geom("geom1").feature("blk18").set("color", "5");
        model.component("comp1").geom("geom1").feature("blk18").set("selresult", false);
        model.component("comp1").geom("geom1").feature("blk19").set("selresult", true);
//    model.component("comp1").geom("geom1").feature("blk19").set("color", "3");
        model.component("comp1").geom("geom1").feature("blk19").set("selresult", false);
        model.component("comp1").geom("geom1").feature("blk20").set("selresult", true);
//    model.component("comp1").geom("geom1").feature("blk20").set("color", "15");
        model.component("comp1").geom("geom1").feature("blk20").set("selresult", false);
        model.component("comp1").geom("geom1").feature("blk22").set("selresult", true);
        model.component("comp1").geom("geom1").feature("blk22").set("color", "6");
        model.component("comp1").geom("geom1").feature("blk22").set("selresult", false);
        model.component("comp1").geom("geom1").feature().copy("blk32", "geom1/blk22");
        model.component("comp1").geom("geom1").run("blk32");
        model.component("comp1").geom("geom1").feature("blk32").setIndex("pos", 28.4, 0);
        model.component("comp1").geom("geom1").feature("blk32").setIndex("pos", 11.3, 2);
        model.component("comp1").geom("geom1").run("blk32");
        model.component("comp1").geom("geom1").feature("blk27").set("selresult", true);
        // model.component("comp1").geom("geom1").feature("blk27").set("color", "3");
        model.component("comp1").geom("geom1").feature("blk27").set("selresult", false);
        model.component("comp1").geom("geom1").feature("blk25").set("selresult", true);
        //model.component("comp1").geom("geom1").feature("blk25").set("color", "3");
        model.component("comp1").geom("geom1").feature("blk25").set("selresult", false);
        model.component("comp1").geom("geom1").feature("blk21").set("selresult", true);
        model.component("comp1").geom("geom1").feature("blk21").set("color", "4");
        model.component("comp1").geom("geom1").feature("blk21").set("selresult", false);
        model.component("comp1").geom("geom1").feature("blk30").set("selresult", true);
        // model.component("comp1").geom("geom1").feature("blk30").set("color", "3");
        model.component("comp1").geom("geom1").feature("blk30").set("selresult", false);
        model.component("comp1").geom("geom1").feature("blk30")
                .set("pos", new String[]{"27.5", "3.5+0.12+0.025+0.038", "23.8"});
        model.component("comp1").geom("geom1").run("blk30");
        model.component("comp1").geom("geom1").runPre("fin");
        model.component("comp1").geom("geom1").feature("blk29").set("selresult", true);
        //model.component("comp1").geom("geom1").feature("blk29").set("color", "2");
        model.component("comp1").geom("geom1").feature("blk29").set("selresult", false);
        model.component("comp1").geom("geom1").feature("blk29")
                .set("pos", new String[]{"27.5", "3.5+0.12+0.025+0.038", "13.7"});
        model.component("comp1").geom("geom1").runPre("fin");
        model.component("comp1").geom("geom1").feature("blk30").set("selresult", true);
        model.component("comp1").geom("geom1").feature("blk29").set("selresult", true);
        model.component("comp1").geom("geom1").feature("blk28").set("selresult", true);
        // model.component("comp1").geom("geom1").feature("blk28").set("color", "3");
        model.component("comp1").geom("geom1").feature("blk28")
                .set("pos", new String[]{"27.5", "3.5+0.12+0.025+0.038", "10.3"});
        model.component("comp1").geom("geom1").runPre("fin");
        model.component("comp1").geom("geom1").feature("blk31").set("selresult", true);
        // model.component("comp1").geom("geom1").feature("blk31").set("color", "2");
        model.component("comp1").geom("geom1").feature("blk31")
                .set("pos", new String[]{"27.5", "3.5+0.12+0.025+0.038", "27.1"});
        model.component("comp1").geom("geom1").run("blk31");
        model.component("comp1").geom("geom1").feature("blk31").set("selresult", false);
        model.component("comp1").geom("geom1").feature("blk30").set("selresult", false);
        model.component("comp1").geom("geom1").feature("blk29").set("selresult", false);
        model.component("comp1").geom("geom1").feature("blk28").set("selresult", false);
        model.component("comp1").geom("geom1").feature("blk14").set("selresult", true);
        // model.component("comp1").geom("geom1").feature("blk14").set("color", "3");
        model.component("comp1").geom("geom1").feature("blk14").set("selresult", false);
        model.component("comp1").geom("geom1").run("blk32");
        model.component("comp1").geom("geom1").feature().remove("blk32");
        model.component("comp1").geom("geom1").feature("blk31").set("selresult", false);
        model.component("comp1").geom("geom1").feature("blk30").set("selresult", false);
        model.component("comp1").geom("geom1").feature("blk29").set("selresult", false);
        model.component("comp1").geom("geom1").feature("blk28").set("selresult", false);
        model.component("comp1").geom("geom1").feature("blk27").set("selresult", true);
        model.component("comp1").geom("geom1").feature("blk27").active(false);
        model.component("comp1").geom("geom1").feature("blk26").set("selresult", true);
        // model.component("comp1").geom("geom1").feature("blk26").set("color", "2");
        model.component("comp1").geom("geom1").feature("blk26").active(false);
        model.component("comp1").geom("geom1").feature().remove("blk26");
        model.component("comp1").geom("geom1").feature().remove("blk27");
        model.component("comp1").geom("geom1").feature("blk25").set("selresult", true);
        model.component("comp1").geom("geom1").feature("blk24").set("selresult", true);
        model.component("comp1").geom("geom1").feature("blk24").set("color", "2");
        model.component("comp1").geom("geom1").feature().remove("blk24");
        model.component("comp1").geom("geom1").feature().remove("blk25");
        model.component("comp1").geom("geom1").feature("blk28").set("selresult", false);
        model.component("comp1").geom("geom1").feature("blk22").set("selresult", true);
        model.component("comp1").geom("geom1").feature("blk23").set("selresult", true);
        //model.component("comp1").geom("geom1").feature("blk23").set("color", "3");
        model.component("comp1").geom("geom1").feature().remove("blk22");
        model.component("comp1").geom("geom1").feature().remove("blk23");
        model.component("comp1").geom("geom1").run("fin");// some


        return model;
    }

    public static void main(String[] args) {
        Model model = run();
        run2(model);
        System.out.printf("Good");
    }

}
